[package]
name = "day17b"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/main.rs"

[features]
full_simulation = ["dep:kdam"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kdam = { version = "0.3.0", optional = true }
